version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: chatapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


