# Application Configuration
spring.application.name=chat-service
server.port=8081

# Security Toggle
app.security.enabled=${APP_SECURITY_ENABLED:true}

security.user.name=${SECURITY_USER_NAME:admin}
security.user.password=${SECURITY_USER_PASSWORD:admin}

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatservice}

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:hyIy1fm6pgbN4k5M64NhSTJlduzHQHchgLziz3AoNec=}
app.jwt.expirationMs=86400000

# Encryption Key (AES-256)
app.encryption.aesKeyBase64=${APP_ENCRYPTION_KEY:oYI7n/41gZhzT+jSSiulAzEwXDrVONpYuNc+t1OskG8=}

# File Upload
app.upload.dir=uploads/avatars
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Logging
logging.level.com.example.chatservice=DEBUG
logging.level.org.springframework.security=DEBUG
